// THIS FILE WILL HAVE A LIST OF ALL THE TYPE OF ACTIONS SO WE
// DON'T MAKE TYPOS WHEN WE HARDCODE THEM IN OUR REDUCERS OR ACTIONS

export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";
export const CHECK_HOST = "CHECK_HOST";
export const CREATE_SESSION = "CREATE_SESSION";
export const FETCH_SESSIONS = "FETCH_SESSIONS";
export const DELETE_SESSION = "DELETE_SESSION";
export const FETCH_SESSION = "FETCH_SESSION";
export const UPDATE_SESSION = "UPDATE_SESSION";
export const HOST_CREATE = "HOST_CREATE";
export const HOST_LOGIN = "HOST_LOGIN";
export const HOST_LOGOUT = "HOST_LOG";
