// THIS FILE WILL HAVE A LIST OF ALL THE TYPE OF ACTIONS SO WE
// DON'T MAKE TYPOS WHEN WE HARDCODE THEM IN OUR REDUCERS OR ACTIONS

export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";
export const CHECK_HOST = "CHECK_HOST";
export const CREATE_CLEANING = "CREATE_SESSION";
export const FETCH_ALL_SESSIONS = "FETCH_ALL_SESSIONS";
export const CLEAN_SESSIONS = "CLEAN_SESSIONS";
export const FETCH_SESSIONS = "FETCH_SESSIONS";
export const DELETE_CLEANING = "DELETE_CLEANING";
export const FETCH_SESSION = "FETCH_SESSION";
export const UPDATE_SESSION = "UPDATE_SESSION";
export const HOST_CREATE = "HOST_CREATE";
export const HOST_LOGIN = "HOST_LOGIN";
export const HOST_LOGOUT = "HOST_LOG";
export const UPDATE_RESOLUTION = "UPDATE_RESOLUTION";
export const NEXT_PAGE = "NEXT_PAGE";
export const PREVIOUS_PAGE = "PREVIOUS_PAGE";
export const UPDATE_PAGE = "UPDATE_PAGE";
export const PICK_DATE = "PICK_DATE";
export const PICK_TIMESLOT = "PICK_TIMESLOT";
export const CLEAN_FORM = "CLEAN_FORM";
